### ISSUE TITLE
Can you please explain how the backward is derived in preprocessCUDA()??

### ISSUE THREAD

**Issue by deepshwang** [slothfulxtx/diff-gaussian-rasterization#1]
Hello!

Thank you for allowing the amazing implementation to public!

I was studying over your implementations and had some questions on how to compute loss gradient w.r.t 3D means due to gradients of depth from rendering procedure, which is implemented in `preprocessCUDA()` of backward... The code snippet is

```
glm::vec3 dL_dmean2;
float mul3 = view[2] * m.x + view[6] * m.y + view[10] * m.z + view[14];
dL_dmean2.x = (view[2] - view[3] * mul3) * dL_ddepth[idx];
dL_dmean2.y = (view[6] - view[7] * mul3) * dL_ddepth[idx];
dL_dmean2.z = (view[10] - view[11] * mul3) * dL_ddepth[idx];
```

1. Can you please explain how this part is derivated?

2. Why use world2view matrix (view), not projective transform matrix (proj) as was used to calculate loss gradient w.r.t. 3D means due to gradients of 2D means? It was a bit confusing for me because the points go through projective transformation to get rasterized, meaning that the backward process to depth info should inevitably encounter projective transformation??

Again, thank you so much for your implementation!

**Comment by slothfulxtx** [comment]
Hi, 
    The depth value of each 3dgs is estimated by transforming the mean3D world coordinate into camera world coordinate, and then extracting the z-value as the depth value. The process can be written as
```
(x_c, y_c, z_c, 1)^T = V (x_w, y_w, z_w, 1)^T
```
Notablely, the view transformation is rigid transformation, which will not change the value of $w$ in $(x,y,z,w)$ coordinate representation. Here $2$ in $dL_dmean2$ represents the second part of $dL_dmean$, more specifically, 3D means due to gradients of depth, not mean2D.

**Comment by XCYYYYY** [comment]
<img width="347" alt="image" src="https://github.com/slothfulxtx/diff-gaussian-rasterization/assets/98203525/1ddff34f-4c3c-4154-b437-f159d517d15c">
this part：- view[3] * mul3；according to the picture upper，should it be ：- view[3] * m.z ？
thx for your great work！

**Comment by slothfulxtx** [comment]
Sorry for the delayed reply. I've received an email which also concern about this question. Here's my reply: 
First, for an ideal view matrix V, it hold the matrix form like this
```
[[R(3*3), t(3*1)], 
[0, 0, 0, 1]]
```
thus for each point p = [x,y,z,1]^T in 3D world, where w=1, the product do not change the value of w. For the following code, 
```
    dL_dmean2.x = (view[2] - view[3] * mul3) * dL_ddepth[idx];
    dL_dmean2.y = (view[6] - view[7] * mul3) * dL_ddepth[idx];
    dL_dmean2.z = (view[10] - view[11] * mul3) * dL_ddepth[idx];  
```
where view array represents the transposed form of view matrix, view[3], view[7] and view[11] is equal to zero. However, I observed that the view matrices for rendering did not always follow the aforementioned form for some dataset (I don't know why.) Thus, the backward process is rewritten from these lines(https://github.com/slothfulxtx/diff-gaussian-rasterization/blob/b1e1cb83e27923579983a9ed19640c6031112b94/cuda_rasterizer/backward.cu#L380).If you treat the view matrix as a special form of projection matrix (transformPoint4x4(m, proj).w is always equal to 1), you can obtain my implementaion. All in all, these codes are not very elegant because they were written when I was not familar with diff-gauss. Sorry for the confusion.
