### ISSUE TITLE
How to disable computing the norm3Ds

### ISSUE THREAD

**Issue by SeaBird-Go** [slothfulxtx/diff-gaussian-rasterization#15]
Hello, thanks for sharing this wonderful work.

I notice that in the latest code, you require the `scales` and `rotations` to be not **None** to support computing the `norm` property. However, in my application, I pass the pre-computed `cov3Ds_precomp`, but it would raise the error since it must need to pass the `scales` and `rotations`.

I'm unfamiliar with the Cuda code, could you help me solve this problem?

**Comment by slothfulxtx** [comment]
Good question! I've just found that the scales and rotations are not neccessary if you pass the precomputed norm3D and cov3D. I'm busy with other works, but I'll fix it in a future version. The simplest solution to your problem is to fill in fake scales and rotations, like a placeholder. In my cuda code, if you pass the precomputed cov3D, it will ignore the computation process from scales and rotations.
![image](https://github.com/user-attachments/assets/0985edf9-af06-4c6e-b6b2-c928cad05557)
