### ISSUE TITLE
about depth map

### ISSUE THREAD

**Issue by cv-lab-x** [slothfulxtx/diff-gaussian-rasterization#2]
hi, thanks for your work, Did your transform the depth map to point3ds for visualization? I test the depth map on bicycle (mip360-datasets), the depths seem are not consistent on multi-view and in some views the bicyle seems distorted.
Looking forward to your reply, thanks! @slothfulxtx

**Comment by slothfulxtx** [comment]
No, I have not visualized the depth map by transformed it into 3d world coordinate system. I think the estimated depth map is not very accurate due to the following problem
![image](https://github.com/slothfulxtx/diff-gaussian-rasterization/assets/37545740/e22abdde-c0b4-4da5-a843-16b492a91a8c)
Suppose the optimized 3d gaussians are nearly flat. For the orange 3d gaussian splatting, the predicted depth is obtained by 2D gaussian splatting located at the center of 3D gaussian. Thus the predicted depth value is smaller than the real depth value (indicated by the black line). For the yellow one, the predicted value is larger than real one.
